#!/bin/bash -e
if [ "$1" = "purge" ] ; then
        update-rc.d sample remove >/dev/null || true
fi

case "$1" in
        purge|remove)
                if [ -d "/opt/local/sample" ]; then
                    rm -R "/opt/local/sample"
                fi
        ;;
        upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
        *)
                echo "$0 called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac
