#!/bin/bash -e
if ! id pi > /dev/null 2>&1 ; then
		useradd -m pi --shell /bin/bash
fi

if [ ! -d /opt/local/sample ]; then
        mkdir "/opt/local/sample"
        chown pi:pi "/opt/local/sample/"
fi

