#!/bin/bash -e
if ! id pi > /dev/null 2>&1 ; then
		useradd -m pi --shell /bin/bash
fi

if [ ! -d /home/pi/sample-minimum ]; then
        mkdir "/home/pi/sample-minimum"
        chown pi:pi "/home/pi/sample-minimum/"
fi

